run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - revive
    - unconvert
    - unparam
    - gosec

issues:
  exclude-use-default: false
