name: ci

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

permissions:
  contents: read

jobs:
  go-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: gofmt check
        run: |
          set -euo pipefail
          files="$(gofmt -l .)"
          if [ -n "$files" ]; then
            echo "gofmt failures:"
            echo "$files"
            exit 1
          fi

      - name: go mod tidy check
        run: |
          set -euo pipefail
          go mod tidy
          git diff --exit-code -- go.mod go.sum

      - name: go test
        run: |
          set -euo pipefail
          go test ./...

      - name: install golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60.3
          args: --timeout=5m
